In [1]:
import torch

In [3]:
a = torch.tensor(1)

In [6]:
a.reshape(1,).shape

torch.Size([1])

In [12]:
b = torch.tensor([1, 4, 3]).reshape(-1, 1)
b, b.shape

(tensor([[1],
         [4],
         [3]]),
 torch.Size([3, 1]))

In [13]:
torch.max(b.flatten())

tensor(4)

In [17]:
torch.argmax(b, dim=0)

tensor([1])

In [18]:
c = torch.zeros_like(b)
c

tensor([[0],
        [0],
        [0]])